{{- if .Values.nextflow.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nf-shard.serviceAccountName" . }}
  namespace: {{ include "nf-shard.namespace" . }}
  labels:
    {{- include "nf-shard.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "nf-shard.fullname" . }}-nextflow
  namespace: {{ include "nf-shard.namespace" . }}
  labels:
    {{- include "nf-shard.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "nf-shard.fullname" . }}-nextflow
  namespace: {{ include "nf-shard.namespace" . }}
  labels:
    {{- include "nf-shard.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "nf-shard.fullname" . }}-nextflow
subjects:
- kind: ServiceAccount
  name: {{ include "nf-shard.serviceAccountName" . }}
  namespace: {{ include "nf-shard.namespace" . }}
{{- end }}
