apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nf-shard.fullname" . }}-secrets
  namespace: {{ include "nf-shard.namespace" . }}
  labels:
    {{- include "nf-shard.labels" . | nindent 4 }}
type: Opaque
stringData:
  app-username: {{ .Values.user.username | quote }}
  app-password: {{ .Values.user.password | quote }}
  app-secret-key: {{ .Values.app.secretKey | quote }}
  default-access-token: {{ .Values.app.defaultAccessToken | quote }}
  postgres-password: {{ .Values.postgres.auth.password | quote }}
  postgres-uri: "postgresql://{{ .Values.postgres.auth.username }}:{{ .Values.postgres.auth.password }}@{{ include "nf-shard.fullname" . }}-postgres:{{ .Values.postgres.service.port }}/{{ .Values.postgres.auth.database }}?schema=public"
